- name: Set fact
  set_fact:
    ip_key: "{{ ansible_host }}"

- name: Print ip variable
  debug:
    msg: "Host: {{ ip_key }}"

- name: Print hosts
  debug:
    msg: "Host: {{ hosts }}"

- name: Fail if not found server info
  when: ip_key not in hosts
  ansible.builtin.fail:
    msg: "Server info haven't been defined"
  